### ISSUE TITLE
Note on confluence version

### ISSUE THREAD

**Issue by mediafreakch** [justmiles/node-atlassian-confluence#1]
Hello,

Your module currently only works for confluence > 5.5. Thought it is worth mentioning (maybe add to readme?)

**Comment by justmiles** [comment]
Thanks for letting me know. I'll add it to the readme.

**Comment by justmiles** [comment]
Updated the readme to [note supported versions](https://github.com/justmiles/node-atlassian-confluence/commit/a4a51bbed1abd420749535c21037814819c47e65)
