### ISSUE TITLE
Example for creating page

### ISSUE THREAD

**Issue by mattimatti** [justmiles/node-atlassian-confluence#2]
Hello, can you please provide example for creating a new page?

Thank you in advance!

**Comment by justmiles** [comment]
Hi @mattimatti,

You can create a new page using the `createContent` function. See below

``` javascript
var confluence = require('atlassian-confluence');

confluence.username = 'your_username';
confluence.password = 'your_password';
confluence.host = 'confluence_host.com';

var page = {
    "type": "page",
    "title": "Example Content title",
    "space": {
        "key": "KEY"
    },
    "body": {
        "storage": {
            "value": "<p>This is a new page</p>",
            "representation": "storage"
        }
    }
};

confluence.createContent(null, page, function (res) {
    console.log(res);
});
```

Check out Atlassian's docs [here](https://docs.atlassian.com/atlassian-confluence/REST/latest/#d3e479), and [here](https://developer.atlassian.com/confdev/confluence-rest-api/confluence-rest-api-examples#ConfluenceRESTAPIExamples-Createanewpage) as well, for more info.

**Comment by mattimatti** [comment]
Thank you @justmiles  !
