### ISSUE TITLE
Add context

### ISSUE THREAD

**Issue by churel** [justmiles/node-atlassian-confluence#3]
Hi,

Would be really cool to be able to add a context to the API query.
When  you look at the official documentation (https://docs.atlassian.com/atlassian-confluence/REST/latest/) they distinct two cases. One with context the other without.

**Comment by justmiles** [comment]
Good idea. I've added a an optional context variable for this. Just be sure to add the leading `/`.

``` javascript
var confluence = require('atlassian-confluence');

confluence.username = 'your_username';
confluence.password = 'your_password';
confluence.host = 'confluence_host.com';
confluence.context = '/wiki'; // optional 

confluence.simpleSearch('help', { limit : 3 }, function (res) {
    if (res) {
        res.results.forEach(function(result) {
            console.log(result.title);
        })
    }
});
```

I've pushed this to npm under version 1.0.3
