### ISSUE TITLE
Connect to non-standard ports

### ISSUE THREAD

**Issue by mariosant** [justmiles/node-atlassian-confluence#6]
Let's say we have a Confluence server listening at `http://domain.net:8090`. This module can't connect to it, which is a pity.

**Comment by justmiles** [comment]
Pull requests are welcomed here.

**Comment by justmiles** [comment]
Check out this banch:  [non-standard-ports](https://github.com/justmiles/node-atlassian-confluence/tree/non-standard-ports)

I don't have a non-ssl confluence host to test against right now. If you're able, test and let me know your results.

**Comment by mariosant** [comment]
Thanks for the quick patch @justmiles! I have one which I will test against it today or tomorrow.

**Comment by justmiles** [comment]
Any luck on this @mariosant?

**Comment by jasonfah** [comment]
@justmiles If I test this branch would you consider merging it ?

**Comment by justmiles** [comment]
@jasonfah sure will. Thanks for the help

**Comment by jasonfah** [comment]
@justmiles the branch appears to be working nicely in regards to setting a custom port.

This line here though;

`@password = options.username or process.env.CONFLUENCE_PASSWORD or process.env.ATLASSIAN_PASSWORD`

Should it be options.password?

**Comment by justmiles** [comment]
Thanks for testing. Yes, that's incorrect. I'll update it.

**Comment by justmiles** [comment]
I've pushed this (#9) to npm under version [2.2.0](https://github.com/justmiles/node-atlassian-confluence/releases/tag/2.2.0)
