### ISSUE TITLE
"HTTPS ERROR: Error: getaddrinfo ENO… https://<my instance>.atlassian.net:443" error

### ISSUE THREAD

**Issue by KenHollandWHY** [justmiles/node-atlassian-confluence#8]
I was just playing around with your package and this morning it stopped being able to access atlassian. Ive tried it from my machine and from another machine on another network. I have also tried using a different confluence instance I own.

**Comment by justmiles** [comment]
You'll get that error when the `CONFLUENCE_HOST` environment variable has the https schema in it. Could you check that variable to ensure it's just `<my instance>.atlassian.net`?

**Comment by KenHollandWHY** [comment]
Great that did it, I feel silly! Thanks for the quick reply
